# Generated by Django 4.2.16 on 2026-05-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='banners/')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='banners/mobile/')),
                ('link', models.CharField(blank=True, max_length=500)),
                ('button_text', models.CharField(blank=True, default='Shop Now', max_length=50)),
                ('position', models.CharField(choices=[('hero', 'Hero Slider'), ('mid', 'Mid-page'), ('popup', 'Popup'), ('sidebar', 'Sidebar')], default='hero', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'banners',
                'ordering': ['order'],
            },
        ),
    ]
